const data = {
  products: [
    {
      name: 'Coat',
      slug: 'coat',
      category: 'Top',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Studio',
      rating: 4.8,
      numReview: 10,
      description: 'high quality jacket',
    },
    {
      name: 'Shirt',
      slug: 'shirt',
      category: 'Top',
      image: '/images/p2.jpg',
      price: 40,
      countInStock: 10,
      brand: 'Studio',
      rating: 5.0,
      numReview: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Pants',
      slug: 'pants',
      category: 'Bottom',
      image: '/images/p3.jpg',
      price: 180,
      countInStock: 10,
      brand: 'Studio',
      rating: 4.6,
      numReview: 10,
      description: 'high quality pants',
    },
    {
      name: 'Jackets',
      slug: 'jackets',
      category: 'Top',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Studio',
      rating: 4.8,
      numReview: 10,
      description: 'high quality jacket',
    },
  ],
};
export default data;
